export default {
  MAIN_COLOR_ACTIVE: '#55CB95',
  MAIN_COLOR_INACTIVE: '#C8C8C8',
  SECONDARY_BACKGROUND_COLOR: '#E0F7EF',
  GREY_COLOR: '#f6f6f6',
  TEXT_DANGER: '#FF4D00',
  TEXT_SUCCESS: '#55CB95',
};
